### ISSUE TITLE
Create "Add New Job" feature for Job Component

### ISSUE THREAD

**Issue by sero-dev** [sero-dev/Home-Angular#5]
Add an "Add New Job" button to the top right of the Job Table
![image](https://user-images.githubusercontent.com/13302928/110518363-03359080-80da-11eb-8e0c-054625f19ebb.png)

On click, the button will display a form (a modal, unless anyone has better ideas) that will allow the user to enter basic information about the job application.

Basic Information will include:
- jobTitle: string (Required)
- employer: string (Required)
- city: string (Required)
- state: string (Required)
- status: string (Required)
- minSalary: number
- maxSalary: number
- dateLastUpdated: DateTime (Not sure, how the conversion will be to the backend DateTime type, but for now it should be a JavaScript DateTime object)

The names I listed will be what the backend expects inside the body of the POST request. There is already a jobs-service.ts file for getting the list of jobs. The logic for sending the new job request to the server should be placed here as well. The docker-compose file is still being developed so you won't be able to test your call to the server yet.

The scope of this issue is the button and form.

Side note: At the moment, we will be sticking to using mostly Bootstrap for our UI until we can develop a unique design for the application.

**Comment by Lbuffier** [comment]
Hello, I want to contribute for this issue
